export const CHANGE_SESSION = 'CHANGE_SESSION'

export const TOGGLE_SIDEBAR_COLLAPSE = 'TOGGLE_SIDEBAR_COLLAPSE'

export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const GET_TRAFFIC_FLOW = 'GET_TRAFFIC_FLOW'

export const GET_WEATHER = 'GET_WEATHER'
